// loandata.js

export const loanData = [
    {
        id: 1,
        title: "Home Loans",
        icon: "IoHome",
        interestRate: "Starting from 3.5%",
        loanAmountRange: "₹100,000 - ₹1,000,000",
        repaymentPeriod: "15 to 30 years",
        specialFeatures: "Flexible repayment options, competitive interest rates, quick approval process.",
        backgroundColor: "linear-gradient(45deg, #ff9a9e 0%, #fad0c4 99%, #fad0c4 100%)",
      },
  {
    id: 2,
    icon: 'AiTwotoneGold',
    title: 'Gold Loans',
    interestRate: '1.5% per month',
    loanAmountRange: '₹1,000 - ₹1,00,000',
    repaymentPeriod: '13 to 12 months',
    loanToValue: 'Up to 75%',
    specialFeatures: 'Instant approval, minimal documentation, option for online gold appraisal.',
    backgroundColor: 'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
  },
  {
    id: 3,
    icon: 'FaCarAlt',
    title: 'Car Loans',
    interestRate: 'Starting from 4%',
    loanAmountRange: '₹1,00,000 - ₹10,00,000',
    repaymentPeriod: '1 to 7 years',
    specialFeatures: 'Competitive interest rates, quick processing, flexible repayment terms.',
    backgroundColor: 'linear-gradient(to top, #fdcbf1 0%, #fdcbf1 1%, #e6dee9 100%)',
  },
  {
    id: 4,
    icon: 'LiaUniversitySolid',
    title: 'Education Loans',
    interestRate: '3.0% to 6.5%',
    loanAmountRange: '₹50,000 - ₹3,00,000',
    repaymentPeriod: 'Grace period during studies + 5 to 15 years',
    specialFeatures: 'No collateral required, flexible repayment options, interest subsidy for eligible students.',
    backgroundColor: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
  },
  {
    id: 5,
    icon: 'FiShoppingBag',
    title: 'Purchase Loans',
    interestRate: 'Starting from 3.75%',
    loanAmountRange: '₹10,000 - ₹5,00,000',
    repaymentPeriod: '10 to 25 years',
    specialFeatures: 'Quick processing, competitive interest rates, tailored solutions for different types of purchases.',
    backgroundColor: 'linear-gradient(to right, #ffecd2 0%, #fcb69f 100%)',
  },
  {
    id: 6,
    icon: 'IoSettingsSharp',
    title: 'Fix and Flip Loans',
    interestRate: '7.5% to 12%',
    loanAmountRange: '₹1,00,000 - ₹20,000,000',
    repaymentPeriod: '6 to 12 months',
    specialFeatures: 'Designed for real estate investors, quick approval, interest-only payments during the renovation period.',
    backgroundColor: 'linear-gradient(60deg, #abecd6 0%, #fbed96 100%)',
  },
];
